### ISSUE TITLE
import dateinfer fails

### ISSUE THREAD

**Issue by johanneshk** [jeffreystarr/dateinfer#8]
Hi!

I installed dateinfer using pip. Upon importing, the following happens:

```
In [1]: import dateinfer
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ed35867f71cb> in <module>()
----> 1 import dateinfer

/home/johannes/anaconda/envs/my_env/lib/python3.4/site-packages/dateinfer/__init__.py in <module>()
      1 __author__ = 'jeffrey.starr@ztoztechnologies.com'
      2 
----> 3 from infer import infer

ImportError: No module named 'infer'

```

Do you have an idea what could be the issue? 

Thanks!
 Johannes

**Comment by t0m** [comment]
`from .infer import infer` seems to solve the issue

**Comment by sp-1234** [comment]
@t0m it doesn't solve it

**Comment by leferrad** [comment]
This issue happens with Python3, and it's related to how the modules are imported. See this: https://stackoverflow.com/questions/28400690/python3-correct-way-to-import-relative-or-absolute

It can be solved by importing modules in an absolute way. So, it means to change these imports:

In dateinfer/ruleproc.py:
- from dateinfer.date_elements import Filler

In dateinfer/infer.py
- from dateinfer.date_elements import *
- from dateinfer.ruleproc import *

In datefinder/__init__.py
- from dateinfer.infer import infer

Is this something tracked to be done? Do I have to make a PR with this?

**Comment by mani619cash** [comment]
@leferrad WORKED

**Comment by KyleStevenYoung** [comment]
>     * from dateinfer.infer import infer

Hey leferrad... just checking, but did you mean to type: 

> In datefinder/init.py
> 
>     _from dateinfer.infer import infer_

or did you mean to type...:

> In dateinfer/init.py
> 
>     _from dateinfer.infer import infer_

I would assume you made a mistake and meant the last one, but I DEFINITELY could be wrong. 
THANKS!

**Comment by leferrad** [comment]
@KyleStevenYoung you can check the proposed changes in PR #11. It is working but, as you can see, this repo is very unmaintained so apparently it will be there without being reviewed/merged eternally... You can fork from that branch if you need it.

**Comment by leferrad** [comment]
Guys I've prepared the following PR to have a stable and maintained version for this repo: https://github.com/leferrad/dateinfer/pull/1

You can try it before the PR is closed, just install it from pip as:
`pip install git+https://github.com/leferrad/dateinfer.git@fix/refactor_package`

Any feedback is welcomed in the PR, and then I will release a version so those interested on using can install it easily.
